// pkg/ui/src/backends/svelte/Textarea.svelte
<!-- Textarea — standard-token multiline field; mirrors the shadcn backend. -->
<script lang="ts">
  import { cn } from '../../core/cn'

  let className: string | undefined = undefined
  export { className as class }
  export let value = ''
  export let disabled = false
  export let readonly = false
  export let placeholder: string | undefined = undefined
</script>

<textarea
  bind:value
  {disabled}
  {readonly}
  {placeholder}
  data-slot="textarea"
  class={cn(
    'flex min-h-16 w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm text-foreground shadow-xs transition-colors outline-none placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 field-sizing-content',
    className,
  )}
  on:input
  on:change
  on:keydown
  on:focus
  on:blur
  {...$$restProps}
></textarea>

// apps/v4/registry/bases/base/ui/textarea.tsx
import * as React from "react"

import { cn } from "@/registry/bases/base/lib/utils"

function Textarea({ className, ...props }: React.ComponentProps<"textarea">) {
  return (
    <textarea
      data-slot="textarea"
      className={cn(
<<<<<<< HEAD
        "cn-textarea placeholder:text-muted-foreground flex field-sizing-content min-h-16 w-full outline-none disabled:cursor-not-allowed disabled:opacity-50",
=======
        "cn-textarea flex field-sizing-content min-h-16 w-full outline-none placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50",
>>>>>>> shadcn/main
        className
      )}
      {...props}
    />
  )
}

export { Textarea }
