// pkg/ui/src/backends/svelte/Input.svelte
<!-- Input — standard-token text field; class string mirrors the shadcn backend. -->
<script lang="ts">
  import { cn } from '../../core/cn'

  let className: string | undefined = undefined
  export { className as class }
  export let value: string | number = ''
  export let type = 'text'
  export let disabled = false
  export let readonly = false
  export let placeholder: string | undefined = undefined

  // Svelte forbids `bind:value` together with a dynamic `type`; set the type via
  // an action and keep `value` controlled so a consumer's `bind:value` still
  // receives updates through the exported prop.
  function typeAttr(node: HTMLInputElement, t: string) {
    node.type = t
    return { update: (next: string) => { node.type = next } }
  }
</script>

<input
  use:typeAttr={type}
  {value}
  {disabled}
  {readonly}
  {placeholder}
  data-slot="input"
  class={cn(
    'flex h-9 w-full min-w-0 rounded-md border border-input bg-transparent px-3 py-1 text-sm text-foreground shadow-xs transition-colors outline-none file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20',
    className,
  )}
  on:input={(e) => (value = e.currentTarget.value)}
  on:input
  on:change
  on:keydown
  on:focus
  on:blur
  {...$$restProps}
/>

// apps/v4/registry/new-york-v4/ui/input.tsx
import * as React from "react"

import { cn } from "@/lib/utils"

function Input({ className, type, ...props }: React.ComponentProps<"input">) {
  return (
    <input
      type={type}
      data-slot="input"
      className={cn(
<<<<<<< HEAD
        "file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-input h-9 w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
        "focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]",
        "aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
=======
        "h-9 w-full min-w-0 rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none selection:bg-primary selection:text-primary-foreground file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm dark:bg-input/30",
        "focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50",
        "aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40",
>>>>>>> shadcn/main
        className
      )}
      {...props}
    />
  )
}

export { Input }
