// pkg/ui/src/backends/svelte/Badge.svelte
<!-- Badge — standard-token label; variant vocabulary mirrors the shadcn backend. -->
<script lang="ts" context="module">
  import { cva, type VariantProps } from 'class-variance-authority'

  export const badgeVariants = cva(
    'inline-flex items-center justify-center w-fit whitespace-nowrap shrink-0 rounded-md border px-2.5 py-0.5 text-xs font-semibold transition-colors focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] focus-visible:outline-none aria-invalid:border-destructive [&>svg]:pointer-events-none overflow-hidden gap-1',
    {
      variants: {
        variant: {
          default: 'bg-primary text-primary-foreground hover:bg-primary/90 border-transparent shadow-sm',
          secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80 border-transparent',
          destructive: 'bg-destructive text-white hover:bg-destructive/90 border-transparent shadow-sm',
          outline: 'text-foreground border-input bg-background shadow-xs hover:bg-accent hover:text-accent-foreground',
        },
      },
      defaultVariants: { variant: 'default' },
    },
  )

  export type BadgeVariant = NonNullable<VariantProps<typeof badgeVariants>['variant']>
</script>

<script lang="ts">
  import { cn } from '../../core/cn'
  let className: string | undefined = undefined
  export { className as class }
  export let variant: BadgeVariant = 'default'
</script>

<span data-slot="badge" class={cn(badgeVariants({ variant }), className)} {...$$restProps}>
  <slot />
</span>

// apps/v4/registry/bases/radix/ui/badge.tsx
import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"
import { Slot } from "radix-ui"

import { cn } from "@/registry/bases/radix/lib/utils"

const badgeVariants = cva(
<<<<<<< HEAD
  "cn-badge inline-flex items-center justify-center w-fit whitespace-nowrap shrink-0 [&>svg]:pointer-events-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive overflow-hidden group/badge",
=======
  "cn-badge group/badge inline-flex w-fit shrink-0 items-center justify-center overflow-hidden whitespace-nowrap focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 [&>svg]:pointer-events-none",
>>>>>>> shadcn/main
  {
    variants: {
      variant: {
        default: "cn-badge-variant-default",
        secondary: "cn-badge-variant-secondary",
        destructive: "cn-badge-variant-destructive",
        outline: "cn-badge-variant-outline",
        ghost: "cn-badge-variant-ghost",
        link: "cn-badge-variant-link",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
)

function Badge({
  className,
  variant = "default",
  asChild = false,
  ...props
}: React.ComponentProps<"span"> &
  VariantProps<typeof badgeVariants> & { asChild?: boolean }) {
  const Comp = asChild ? Slot.Root : "span"

  return (
    <Comp
      data-slot="badge"
      data-variant={variant}
      className={cn(badgeVariants({ variant }), className)}
      {...props}
    />
  )
}

export { Badge, badgeVariants }
